[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# Remember that a crate is a collection of Rust source code files
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"